title: Orkhan Shahmuradli - Personal Portfolio
baseurl: /personal-website
url: https://orkhan8.github.io

markdown: kramdown
exclude: ["README.md", "Gemfile", "Gemfile.lock"]

# Include all files by default
include: ["_layouts", "styles.css", "scripts.js", "media"]
